### ISSUE TITLE
Swict to be selected by default

### ISSUE THREAD

**Issue by sharmapn** [yjg30737/pyqt-switch#1]
Hello,

Thank you for this swicth. I am using it in my application.

Just wondering of tehre was a way to ensure that the swicth is turned on (selected) by default.

Thanks in advance.

**Comment by yjg30737** [comment]
There is no way right now. But it is not hard to implement that feature so i will add it and let you know.

**Comment by sharmapn** [comment]
Hey, in the meantime, I used this approach to click the switch automatically upon load

from PyQt5.QtTest import QTest
from PyQt5.QtCore import Qt 

#the switch should be in combined mode by default
#Click the button
QTest.mouseClick(switch, Qt.LeftButton)

**Comment by yjg30737** [comment]
There you go. I've just finished that feature and you can use below:
```python
`isChecked()`
`setChecked(f: bool)`
```
You can use it as in example on README.

**Comment by sharmapn** [comment]
Thank you so much.

I have used this feature in my QGIS Geoprivacy plugin, with a 5-minute video on YouTube: https://www.youtube.com/watch?v=gq4wX3kMTfE

The plugin can be downloaded from GitHub https://github.com/sharmapn/MapSafe-QGIS-plugin
Help guide here: https://sharmapn.github.io/MapSafeQGISGeoPrivPlugin/

**Comment by yjg30737** [comment]
It's great that you find my widget useful ! Your application looks great ! I can't imagine your huge effort to make it.
I've just liked your video and subscribed as well.

**Comment by sharmapn** [comment]
Thank you so much Jung!
Is there a way to control the X and Y coordinates of the switch? 
It would be nice to vertically align the switch with the Tabbed Pane under it.
If you refer to the video, the label of the video is a bit left to the Tabbed Pane.

**Comment by yjg30737** [comment]
You want to set the x and y coordinates of the switch(inner circle to me) rather than resizing it inside (which can be done by setCircleDiameter)? I can do that, but i want to do it in a different sort of way.
It would be nice to add the feature to set margin or padding than add the feature which absolutely changing the coordinates.
